language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

git:
  depth: false
  quiet: true

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - source $TRAVIS_BUILD_DIR/install.sh

script:
  - $TRAVIS_BUILD_DIR/build.sh build_platform esp8266

notifications:
  email:
    on_success: change
    on_failure: change
