mqtt:
  broker: your.mqtt.ip.address
  port: 1883
  client_id: home-assistant-1
  username: YOURUSERNAME
  password: YOURPASSWORD

light:
  - platform: mqtt
    schema: json
    name: "Stairs Strip"
    state_topic: "bruh/stairs"
    command_topic: "bruh/stairs/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle  
    brightness: true
    rgb: true
    optimistic: false
    qos: 0

input_number:
  stairs_animation_speed:
    name: Stairs Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
automation: 
  - alias: "Stairs Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.stairs_animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/stairs/set"
          payload: '{"transition":{{ trigger.to_state.state | int }}}'
