name: Github Arduino Library CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: pre-install
      run: |
        source install.sh
    - name: test platform
      run: |
        ./build.sh build_platform esp8266

